#!/bin/sh
# 
# Module: pallon
# 
# **** License ****
# Version: VPL 1.0
# 
# The contents of this file are subject to the Vyatta Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.vyatta.com/vpl
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2006, 2007 Vyatta, Inc.
# All Rights Reserved.
# 
# Author: Rick Balocca
# Date: 2007
# Description:
# 
# **** End License ****

# first make sure that all pppd's are stopped
poff -a 2>/dev/null >/dev/null

# now start them all back up
for i in `cd /etc/ppp/peers; ls wan* 2>/dev/null`
do
	echo -n "STARTED ">>/var/log/$i.log
	date>>/var/log/$i.log
	pppd call $i >>/var/log/$i.log&
done
