#!/bin/sh
# Module: vyatta-ppp
# 
# **** License ****
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2006, 2007 Vyatta, Inc.
# All Rights Reserved.
# 
# Author: Rick Balocca
# Date: 2006
# Description:
# 
# **** End License ****

[ x"/etc/ppp/peers/wan*" = x ] && exit 0

ACTION=$1
WANPIPE=$2

if [ "${WANPIPE}" ]
then
	WANPIPE_INDEX=`expr ${WANPIPE} - 1`.1
else
	WANPIPE_INDEX=
fi

#LOG_FILE=/tmp/${WANPIPE_INDEX}vywan.log
LOG_FILE=/dev/null
PPPD_LOG_FILE=/var/log/wan${WANPIPE_INDEX}.log
PPP_INTERFACE_FILE=wan${WANPIPE_INDEX}
PPP_OFFSETS_DIR=/tmp/.offsets/ppp/
PPP_OFFSETS_FILE_WAN=${PPP_OFFSETS_DIR}wan${WANPIPE_INDEX}

start()
{
        grep -q 'VYATTA version' /etc/ppp/options ||
        cp /usr/share/vyatta-ppp/* /etc/ppp/.

	if [ "${WANPIPE}" ]
	then
		echo "Starting pppd">>${LOG_FILE}
		date>>${LOG_FILE}
		rm -rf ${PPP_OFFSETS_FILE_WAN} 2>>/dev/null
		/sbin/pon ${PPP_INTERFACE_FILE}</dev/null >>${PPPD_LOG_FILE}  2>&1 &
	else
		echo "Starting ALL pppd ... ">>${LOG_FILE}
		rm -rf ${PPP_OFFSETS_DIR}* 2>>/dev/null
		/sbin/pallon >>${LOG_FILE} 2>&1
		echo "Starting ALL pppd done">>${LOG_FILE}
	fi
}

stop()
{
	echo "Stopping pppd ${WANPIPE}...">>${LOG_FILE}
	if [ "${WANPIPE}" ]
	then
		date>>${LOG_FILE}
		/sbin/poff ${PPP_INTERFACE_FILE}
		rm -rf ${PPP_OFFSETS_FILE_WAN} 2>>/dev/null
	else
		/sbin/poff -a 
		rm -rf ${PPP_OFFSETS_DIR}* 2>>/dev/null
	fi
	echo "Stopping pppd done">>${LOG_FILE}
}

case "$ACTION" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
